main = "src/index.ts"
compatibility_date = "2023-07-17"

name = "tiktok-embeds"
routes = ["vm.dstn.to/*"]
workers_dev = false

[env.dev]
name = "tiktok-embeds-debug"
routes = ["vmd.dstn.to/*"]
workers_dev = true