name = "tiktok-embeds"
type = "webpack"

webpack_config = "webpack.config.js"
workers_dev = false

routes = ["vm.dstn.to/*"]
zone_id = "348792876bb474a7cadf69be26c00b5c"
account_id = "3e4e267fb0f575f02c3d6ecd0c65f3cd"